version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
