language: python

cache:
  - pip

python:
  - '3.7'
  - '2.7'

addons:
  apt:
    update: true
    packages:
      - freeglut3-dev

install:
  - pip install --upgrade pip setuptools wheel
  - pip install Cython
  - pip install .[all]

script:
  - pip install hacking pytest
  - flake8 .
  - pytest -v tests

sudo: false

branches:
  only:
    - master
