language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install --upgrade pip setuptools wheel
  - pip install Cython
  - python setup.py develop

script:
  - pip install hacking pytest
  - flake8 .
  - pytest -v tests

sudo: false

branches:
  only:
    - master
