language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install --upgrade pip setuptools wheel
  - pip install autopep8
  - pip install Cython
  - python setup.py develop

script:
  - pip install hacking pytest
  - autopep8 -r . --diff --exit-code
  - pytest -v tests

sudo: false

branches:
  only:
    - master
