"""
Gazebo configuration file generators.

Generates world and plugin configuration files.
"""


from __future__ import annotations

from typing import Any


def generate_gazebo_config(
    physics: dict[str, Any],
    plugins: list[dict[str, Any]],
) -> str:
    """
    Generate Gazebo world configuration snippet.

    Parameters
    ----------
    physics : dict
        Physics configuration with:
        - solver: Physics engine (ode, bullet, simbody, dart)
        - stepSize: Simulation step size in seconds
        - realTimeFactor: Real-time factor
    plugins : list
        List of plugin configurations with:
        - name: Plugin name
        - filename: Plugin library filename
        - enabled: Whether plugin is enabled
        - parameters: Dict of plugin parameters

    Returns
    -------
    str
        Gazebo SDF/world configuration snippet.
    """
    solver = physics.get("solver", "ode")
    step_size = physics.get("stepSize", 0.001)
    rtf = physics.get("realTimeFactor", 1.0)

    lines = [
        "<!-- Gazebo Configuration Generated by scikit-robot -->",
        "",
        f'<physics name="default_physics" type="{solver}">',
        f"  <max_step_size>{step_size}</max_step_size>",
        f"  <real_time_factor>{rtf}</real_time_factor>",
        f"  <real_time_update_rate>{int(1 / step_size)}</real_time_update_rate>",
        "</physics>",
        "",
    ]

    # Plugins
    for plugin in plugins:
        if not plugin.get("enabled", True):
            continue

        name = plugin["name"]
        filename = plugin["filename"]
        params = plugin.get("parameters", {})

        lines.append(f'<plugin filename="{filename}" name="{name}">')
        for key, value in params.items():
            lines.append(f"  <{key}>{value}</{key}>")
        lines.append("</plugin>")
        lines.append("")

    return "\n".join(lines)


def generate_ros2_control_xacro(
    joints: list[dict[str, Any]],
    hardware_interface: str = "gazebo_ros2_control/GazeboSystem",
) -> str:
    """
    Generate ros2_control URDF/Xacro snippet for Gazebo.

    Parameters
    ----------
    joints : list
        List of joint configurations with:
        - name: Joint name
        - type: Joint type (revolute, prismatic, etc.)
    hardware_interface : str
        Hardware interface plugin name.

    Returns
    -------
    str
        ros2_control Xacro snippet.
    """
    lines = [
        "<!-- ros2_control Configuration for Gazebo -->",
        "<!-- Generated by scikit-robot -->",
        "",
        '<ros2_control name="GazeboSystem" type="system">',
        "  <hardware>",
        f"    <plugin>{hardware_interface}</plugin>",
        "  </hardware>",
    ]

    for joint in joints:
        if joint.get("type") == "fixed":
            continue

        # Mimic joints are passively driven through the URDF <mimic> tag,
        # which gz_ros2_control enforces directly. Giving them a command
        # interface would conflict with that constraint, so skip them.
        if joint.get("isMimic"):
            continue

        name = joint["name"]
        lines.append(f'  <joint name="{name}">')
        lines.append('    <command_interface name="position"/>')
        lines.append('    <command_interface name="velocity"/>')
        lines.append('    <state_interface name="position"/>')
        lines.append('    <state_interface name="velocity"/>')
        lines.append('    <state_interface name="effort"/>')
        lines.append("  </joint>")

    lines.append("</ros2_control>")
    lines.append("")
    lines.append("<gazebo>")
    lines.append('  <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">')
    lines.append("    <parameters>$(find robot_config)/config/controllers.yaml</parameters>")
    lines.append("  </plugin>")
    lines.append("</gazebo>")

    return "\n".join(lines)
