"""
Gazebo configuration file generators.

Generates world and plugin configuration files.
"""


from __future__ import annotations

from typing import Any
from typing import Iterable
from typing import Sequence
import xml.etree.ElementTree as ET


# gz_ros2_control, the ros2_control integration for Gazebo (formerly
# "Ignition").  Gazebo Classic and its gazebo_ros2_control plugin reached
# end of life in January 2025 and are not supported here.
GZ_HARDWARE_PLUGIN = "gz_ros2_control/GazeboSimSystem"
GZ_SYSTEM_PLUGIN_FILENAME = "libgz_ros2_control-system.so"
GZ_SYSTEM_PLUGIN_NAME = "gz_ros2_control::GazeboSimROS2ControlPlugin"


def generate_gazebo_config(
    physics: dict[str, Any],
    plugins: list[dict[str, Any]],
) -> str:
    """
    Generate Gazebo world configuration snippet.

    Parameters
    ----------
    physics : dict
        Physics configuration with:
        - solver: Physics engine (ode, bullet, simbody, dart)
        - step_size: Simulation step size in seconds
        - real_time_factor: Real-time factor
    plugins : list
        List of plugin configurations with:
        - name: Plugin name
        - filename: Plugin library filename
        - enabled: Whether plugin is enabled
        - parameters: Dict of plugin parameters

    Returns
    -------
    str
        Gazebo SDF/world configuration snippet.
    """
    solver = physics.get("solver", "ode")
    step_size = physics.get("step_size", 0.001)
    rtf = physics.get("real_time_factor", 1.0)

    lines = [
        "<!-- Gazebo Configuration Generated by scikit-robot -->",
        "",
        f'<physics name="default_physics" type="{solver}">',
        f"  <max_step_size>{step_size}</max_step_size>",
        f"  <real_time_factor>{rtf}</real_time_factor>",
        f"  <real_time_update_rate>{int(1 / step_size)}</real_time_update_rate>",
        "</physics>",
        "",
    ]

    # Plugins
    for plugin in plugins:
        if not plugin.get("enabled", True):
            continue

        name = plugin["name"]
        filename = plugin["filename"]
        params = plugin.get("parameters", {})

        lines.append(f'<plugin filename="{filename}" name="{name}">')
        for key, value in params.items():
            lines.append(f"  <{key}>{value}</{key}>")
        lines.append("</plugin>")
        lines.append("")

    return "\n".join(lines)


def build_ros2_control_elements(
    joint_names: Iterable[str],
    package_name: str,
    controllers_file: str = "controllers.yaml",
    name: str = "GazeboSimSystem",
    command_interfaces: Sequence[str] = ("position",),
    state_interfaces: Sequence[str] = ("position", "velocity"),
) -> tuple[ET.Element, ET.Element]:
    """
    Build the ``<ros2_control>`` and ``<gazebo>`` elements for gz_ros2_control.

    Callers either serialize these into a standalone xacro snippet (see
    :func:`generate_ros2_control_xacro`) or append them to a URDF tree.

    Parameters
    ----------
    joint_names : iterable of str
        Joints to expose. Fixed and mimic joints must already be filtered
        out: a mimic joint is constrained by the URDF ``<mimic>`` tag,
        which gz_ros2_control enforces itself, so commanding it too would
        fight that constraint.
    package_name : str
        ROS package the plugin loads its controller config from
        (``$(find <package_name>)/config/<controllers_file>``).
    controllers_file : str
        Controller config filename inside that package's ``config/``.
    name : str
        Name attribute of the ``<ros2_control>`` element.
    command_interfaces : sequence of str
        Command interfaces to declare per joint.
    state_interfaces : sequence of str
        State interfaces to declare per joint.

    Returns
    -------
    tuple of xml.etree.ElementTree.Element
        The ``<ros2_control>`` and ``<gazebo>`` elements.
    """
    ros2_control = ET.Element("ros2_control", attrib={"name": name,
                                                      "type": "system"})
    hardware = ET.SubElement(ros2_control, "hardware")
    ET.SubElement(hardware, "plugin").text = GZ_HARDWARE_PLUGIN

    for joint_name in joint_names:
        joint_el = ET.SubElement(ros2_control, "joint",
                                 attrib={"name": joint_name})
        for interface in command_interfaces:
            ET.SubElement(joint_el, "command_interface",
                          attrib={"name": interface})
        for interface in state_interfaces:
            ET.SubElement(joint_el, "state_interface",
                          attrib={"name": interface})

    gazebo = ET.Element("gazebo")
    plugin = ET.SubElement(gazebo, "plugin",
                           attrib={"filename": GZ_SYSTEM_PLUGIN_FILENAME,
                                   "name": GZ_SYSTEM_PLUGIN_NAME})
    ET.SubElement(plugin, "parameters").text = (
        "$(find {})/config/{}".format(package_name, controllers_file))
    return ros2_control, gazebo


def generate_ros2_control_xacro(
    joints: list[dict[str, Any]],
    package_name: str = "robot_config",
    controllers_file: str = "controllers.yaml",
) -> str:
    """
    Generate a ros2_control URDF/Xacro snippet for Gazebo.

    Parameters
    ----------
    joints : list
        List of joint configurations with:
        - name: Joint name
        - type: Joint type (revolute, prismatic, etc.)
        - is_mimic: Whether the joint is passively driven by another
    package_name : str
        ROS package the plugin loads its controller config from
        (``$(find <package_name>)``).  Pass the exported package's name.
    controllers_file : str
        Controller config filename inside that package's ``config/``.

    Returns
    -------
    str
        ros2_control Xacro snippet.
    """
    joint_names = [joint["name"] for joint in joints
                   if joint.get("type") != "fixed"
                   and not joint.get("is_mimic")]
    ros2_control, gazebo = build_ros2_control_elements(
        joint_names,
        package_name=package_name,
        controllers_file=controllers_file,
        command_interfaces=("position", "velocity"),
        state_interfaces=("position", "velocity", "effort"))

    for element in (ros2_control, gazebo):
        if hasattr(ET, "indent"):
            ET.indent(element, space="  ", level=0)

    return "\n".join([
        "<!-- ros2_control Configuration for Gazebo -->",
        "<!-- Generated by scikit-robot -->",
        "",
        ET.tostring(ros2_control, encoding="unicode"),
        "",
        ET.tostring(gazebo, encoding="unicode"),
    ])
