"""
MoveIt2 configuration file generators.

Generates SRDF and controller configuration files.
"""


from __future__ import annotations

from typing import Any


def generate_srdf(
    robot_name: str,
    planning_groups: list[dict[str, Any]],
    disabled_collision_pairs: list[tuple[str, str]],
) -> str:
    """
    Generate SRDF (Semantic Robot Description Format) content.

    Parameters
    ----------
    robot_name : str
        Name of the robot.
    planning_groups : list
        List of planning group definitions. Each group should have:
        - name: Group name
        - joints: List of joint names
        - endEffectorLink: Optional end effector link name
        - baseLink: Optional base link name
    disabled_collision_pairs : list
        List of (link1, link2) tuples for disabled collisions.

    Returns
    -------
    str
        SRDF XML content.
    """
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- SRDF Generated by scikit-robot -->",
        f'<robot name="{robot_name}">',
    ]

    # Planning groups
    for group in planning_groups:
        lines.append(f'  <group name="{group["name"]}">')
        for joint in group.get("joints", []):
            lines.append(f'    <joint name="{joint}" />')
        lines.append("  </group>")
        lines.append("")

    # End effectors
    for group in planning_groups:
        ee_link = group.get("endEffectorLink")
        if ee_link:
            ee_name = f"{group['name']}_eef"
            parent = ee_link
            lines.append(f'  <end_effector name="{ee_name}" parent_link="{parent}" group="{group["name"]}" />')

    lines.append("")
    lines.append("  <!-- Disabled Collisions -->")

    # Disabled collision pairs
    for link1, link2 in disabled_collision_pairs:
        lines.append(f'  <disable_collisions link1="{link1}" link2="{link2}" reason="User defined" />')

    lines.append("</robot>")

    return "\n".join(lines)


def generate_controllers_yaml(
    controllers: list[dict[str, Any]],
    update_rate: int = 100,
) -> str:
    """
    Generate ros2_control controllers.yaml configuration.

    Parameters
    ----------
    controllers : list
        List of controller definitions. Each should have:
        - name: Controller name
        - type: Controller type (joint_trajectory_controller, gripper_controller, etc.)
        - joints: List of joint names
    update_rate : int
        Controller update rate in Hz.

    Returns
    -------
    str
        YAML configuration content.
    """
    lines = [
        "# ros2_control Configuration",
        "# Generated by scikit-robot",
        "",
        "controller_manager:",
        "  ros__parameters:",
        f"    update_rate: {update_rate}",
        "",
    ]

    # Type mapping
    type_map = {
        "joint_trajectory_controller": "joint_trajectory_controller/JointTrajectoryController",
        "gripper_controller": "gripper_action_controller/GripperActionController",
        "position_controller": "position_controllers/JointGroupPositionController",
    }

    for controller in controllers:
        name = controller["name"]
        ctrl_type = controller.get("type", "joint_trajectory_controller")
        joints = controller.get("joints", [])

        full_type = type_map.get(ctrl_type, ctrl_type)

        lines.append(f"{name}:")
        lines.append("  ros__parameters:")
        lines.append(f"    type: {full_type}")
        lines.append("    joints:")
        for joint in joints:
            lines.append(f"      - {joint}")
        lines.append("")

    return "\n".join(lines)
