"""
MoveIt2 configuration file generators.

Generates SRDF and controller configuration files.
"""


from __future__ import annotations

from typing import Any


def generate_srdf(
    robot_name: str,
    planning_groups: list[dict[str, Any]],
    disabled_collision_pairs: list[tuple[str, str]],
    virtual_joint: dict[str, str] | None = None,
    group_states: list[dict[str, Any]] | None = None,
    disabled_collision_reason: str = "User defined",
) -> str:
    """
    Generate SRDF (Semantic Robot Description Format) content.

    Parameters
    ----------
    robot_name : str
        Name of the robot.
    planning_groups : list
        List of planning group definitions. Each group should have:
        - name: Group name
        - joints: List of joint names
        - end_effector_link: Optional end effector link name
        - base_link: Optional base link name
    disabled_collision_pairs : list
        List of (link1, link2) tuples for disabled collisions.
    virtual_joint : dict, optional
        Virtual joint anchoring the robot to a fixed frame, with keys
        ``name``, ``type``, ``parent_frame`` and ``child_link``. MoveIt
        needs one to plan against a world frame.
    group_states : list, optional
        Named poses. Each entry has ``name``, ``group`` and
        ``joint_values`` (a joint name to value mapping).
    disabled_collision_reason : str
        ``reason`` attribute written on every ``disable_collisions``
        entry.

    Returns
    -------
    str
        SRDF XML content.
    """
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- SRDF Generated by scikit-robot -->",
        f'<robot name="{robot_name}">',
    ]

    # Planning groups
    for group in planning_groups:
        lines.append(f'  <group name="{group["name"]}">')
        for joint in group.get("joints", []):
            lines.append(f'    <joint name="{joint}" />')
        lines.append("  </group>")
        lines.append("")

    # End effectors
    for group in planning_groups:
        ee_link = group.get("end_effector_link")
        if ee_link:
            ee_name = f"{group['name']}_eef"
            parent = ee_link
            lines.append(f'  <end_effector name="{ee_name}" parent_link="{parent}" group="{group["name"]}" />')

    if virtual_joint:
        lines.append("")
        lines.append(
            '  <virtual_joint name="{}" type="{}" parent_frame="{}" '
            'child_link="{}" />'.format(
                virtual_joint["name"], virtual_joint.get("type", "fixed"),
                virtual_joint["parent_frame"], virtual_joint["child_link"]))

    for state in group_states or []:
        lines.append("")
        lines.append('  <group_state name="{}" group="{}">'.format(
            state["name"], state["group"]))
        for joint, value in state.get("joint_values", {}).items():
            lines.append('    <joint name="{}" value="{}" />'.format(
                joint, value))
        lines.append("  </group_state>")

    lines.append("")
    lines.append("  <!-- Disabled Collisions -->")

    # Disabled collision pairs
    for link1, link2 in disabled_collision_pairs:
        lines.append(
            '  <disable_collisions link1="{}" link2="{}" reason="{}" />'.format(
                link1, link2, disabled_collision_reason))

    lines.append("</robot>")

    return "\n".join(lines)


def generate_controllers_yaml(
    controllers: list[dict[str, Any]],
    update_rate: int = 100,
) -> str:
    """
    Generate ros2_control controllers.yaml configuration.

    Parameters
    ----------
    controllers : list
        List of controller definitions. Each should have:
        - name: Controller name
        - type: Controller type (joint_trajectory_controller, gripper_controller, etc.)
        - joints: List of joint names
    update_rate : int
        Controller update rate in Hz.

    Returns
    -------
    str
        YAML configuration content.
    """
    # Type mapping
    type_map = {
        "joint_trajectory_controller": "joint_trajectory_controller/JointTrajectoryController",
        "gripper_controller": "gripper_action_controller/GripperActionController",
        "position_controller": "position_controllers/JointGroupPositionController",
    }

    lines = [
        "# ros2_control Configuration",
        "# Generated by scikit-robot",
        "",
        "controller_manager:",
        "  ros__parameters:",
        f"    update_rate: {update_rate}",
        "",
    ]

    # ros2_control resolves a controller's ``type`` from the controller
    # manager's OWN parameter namespace when spawning, so the type
    # declarations must be nested here, not in the controllers' node
    # namespaces.
    for controller in controllers:
        name = controller["name"]
        ctrl_type = controller.get("type", "joint_trajectory_controller")
        full_type = type_map.get(ctrl_type, ctrl_type)
        lines.append(f"    {name}:")
        lines.append(f"      type: {full_type}")
        lines.append("")

    for controller in controllers:
        name = controller["name"]
        joints = controller.get("joints", [])

        lines.append(f"{name}:")
        lines.append("  ros__parameters:")
        lines.append("    joints:")
        for joint in joints:
            lines.append(f"      - {joint}")
        lines.append("")

    return "\n".join(lines)
